language: objective-c
osx_image: xcode7.1
env:
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s" SDK=iphonesimulator10.0
    - DESTINATION="OS=10.0,name=iPhone 6s Plus" SDK=iphonesimulator10.0
branches:
  only:
    - master
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install --project-dir=Example
script:
  - set -o pipefail
  - xcodebuild -workspace XYDoughnutChart.xcworkspace -scheme XYDoughnutChartDemo -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
