language: objective-c
osx_image: xcode7.1
env:
  matrix:
    - DESTINATION="OS=9.1,name=iPhone 6s" SDK=iphonesimulator9.1
    - DESTINATION="OS=9.1,name=iPhone 6s Plus" SDK=iphonesimulator9.1
branches:
  only:
    - master
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - cd Example && pod install && cd -
script:
  - set -o pipefail
  - xcodebuild -workspace XYDoughnutChart.xcworkspace -scheme XYDoughnutChartDemo -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
